version: '3'

volumes:
  database:
  redis:

networks:
  frontend:
  backend:

services:
  php-fpm:
    build: .docker/php-fpm
    volumes:
      - .:/var/www/app
    networks:
      - backend
    ports:
      - "9000:9000"

  php-console:
    build: .docker/php-console
    volumes:
      - ./:/var/www/app
    networks:
      - backend

  nginx:
    build: .docker/nginx
    volumes:
      - .:/var/www/app
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    links:
      - php-fpm

  db:
    env_file:
     - .env
    build: .docker/postgres
    container_name: ${DB_CONNECTION}
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
     - backend

  beanstalkd:
    env_file:
      - .env
    build: .docker/beanstalkd
    container_name: ${BEANSTALKD_HOST}
    ports:
      - "${BEANSTALKD_PORT}:11300"
    privileged: true
    networks:
      - backend

  redis:
    container_name: ${REDIS_HOST}
    build:
      context: .docker/redis
      args:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend